SELECT TOP (1000) [ID]
      ,[Nom]
      ,[Prenom]
      ,[Genre]
      ,[NiveauAcademique]
      ,[Age]
      ,[OrientationS]
      ,[Courriel]
      ,[Username]
      ,[MotDePasse]
      ,[Est_Active]
      ,[DateCreationProfil]
      ,[CritereRechercheID]
      ,[ModelPsycologiqueID]
  FROM [SO2M].[dbo].[Utilisateurs]
