USE [master]
GO
/****** Object:  Database [SO2Mv4]    Script Date: 16/06/2024 15:11:25 ******/
CREATE DATABASE [SO2Mv4]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SO2Mv4', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\SO2Mv4.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SO2Mv4_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\SO2Mv4_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [SO2Mv4] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SO2Mv4].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SO2Mv4] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SO2Mv4] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SO2Mv4] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SO2Mv4] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SO2Mv4] SET ARITHABORT OFF 
GO
ALTER DATABASE [SO2Mv4] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [SO2Mv4] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SO2Mv4] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SO2Mv4] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SO2Mv4] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SO2Mv4] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SO2Mv4] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SO2Mv4] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SO2Mv4] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SO2Mv4] SET  ENABLE_BROKER 
GO
ALTER DATABASE [SO2Mv4] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SO2Mv4] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SO2Mv4] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SO2Mv4] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SO2Mv4] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SO2Mv4] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [SO2Mv4] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SO2Mv4] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [SO2Mv4] SET  MULTI_USER 
GO
ALTER DATABASE [SO2Mv4] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SO2Mv4] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SO2Mv4] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SO2Mv4] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SO2Mv4] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [SO2Mv4] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [SO2Mv4] SET QUERY_STORE = ON
GO
ALTER DATABASE [SO2Mv4] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [SO2Mv4]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 16/06/2024 15:11:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CritereRecherches]    Script Date: 16/06/2024 15:11:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CritereRecherches](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[AgeMin] [int] NULL,
	[AgeMax] [int] NULL,
	[NiveauAcademique] [nvarchar](max) NULL,
	[Genre] [nvarchar](max) NULL,
	[OrientationS] [nvarchar](max) NULL,
	[Ville] [nvarchar](max) NULL,
	[RayonRecherche] [int] NULL,
 CONSTRAINT [PK_CritereRecherches] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Messages]    Script Date: 16/06/2024 15:11:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Messages](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ExpediteurId] [int] NOT NULL,
	[DestinataireId] [int] NOT NULL,
	[Contenu] [nvarchar](max) NOT NULL,
	[DateEnvoye] [datetime2](7) NOT NULL,
	[Lu] [bit] NOT NULL,
 CONSTRAINT [PK_Messages] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Photos]    Script Date: 16/06/2024 15:11:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Photos](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Url] [nvarchar](max) NULL,
	[DateAjout] [date] NULL,
	[PhotoProfil] [bit] NULL,
	[UtilisateurId] [int] NULL,
 CONSTRAINT [PK_Photos] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Utilisateurs]    Script Date: 16/06/2024 15:11:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Utilisateurs](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nom] [nvarchar](max) NULL,
	[Prenom] [nvarchar](max) NULL,
	[Genre] [nvarchar](max) NULL,
	[NiveauAcademique] [nvarchar](max) NULL,
	[Age] [int] NULL,
	[OrientationS] [nvarchar](max) NULL,
	[Courriel] [nvarchar](max) NULL,
	[Utilisateur1] [nvarchar](max) NULL,
	[Username] [nvarchar](max) NULL,
	[MotDePasse] [nvarchar](max) NULL,
	[EstActive] [bit] NULL,
	[DateCreationProfil] [date] NULL,
	[CritereRechercheId] [int] NULL,
	[Modele1Axe1] [int] NULL,
	[Modele1Axe2] [int] NULL,
	[Modele1Axe3] [int] NULL,
 CONSTRAINT [PK_Utilisateurs] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Index [IX_Photos_UtilisateurId]    Script Date: 16/06/2024 15:11:25 ******/
CREATE NONCLUSTERED INDEX [IX_Photos_UtilisateurId] ON [dbo].[Photos]
(
	[UtilisateurId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Utilisateurs_CritereRechercheId]    Script Date: 16/06/2024 15:11:25 ******/
CREATE NONCLUSTERED INDEX [IX_Utilisateurs_CritereRechercheId] ON [dbo].[Utilisateurs]
(
	[CritereRechercheId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Photos]  WITH CHECK ADD  CONSTRAINT [FK_Photos_Utilisateurs_UtilisateurId] FOREIGN KEY([UtilisateurId])
REFERENCES [dbo].[Utilisateurs] ([Id])
GO
ALTER TABLE [dbo].[Photos] CHECK CONSTRAINT [FK_Photos_Utilisateurs_UtilisateurId]
GO
ALTER TABLE [dbo].[Utilisateurs]  WITH CHECK ADD  CONSTRAINT [FK_Utilisateurs_CritereRecherches_CritereRechercheId] FOREIGN KEY([CritereRechercheId])
REFERENCES [dbo].[CritereRecherches] ([Id])
GO
ALTER TABLE [dbo].[Utilisateurs] CHECK CONSTRAINT [FK_Utilisateurs_CritereRecherches_CritereRechercheId]
GO
USE [master]
GO
ALTER DATABASE [SO2Mv4] SET  READ_WRITE 
GO
